import { Env } from '../types';

interface GitHubRepoResult {
    success: boolean;
    repoUrl?: string;
    error?: string;
}

interface GitHubPushResult {
    success: boolean;
    commitSha?: string;
    error?: string;
}

const GITHUB_API = 'https://api.github.com';

/**
 * Create a new GitHub repository for the landing page
 */
export async function createGitHubRepo(
    repoName: string,
    env: Env
): Promise<GitHubRepoResult> {
    try {
        // First, check if repo already exists
        const checkResponse = await fetch(`${GITHUB_API}/repos/local-brands/${repoName}`, {
            headers: {
                Authorization: `Bearer ${env.GITHUB_TOKEN}`,
                Accept: 'application/vnd.github.v3+json',
                'User-Agent': 'LocalBrands-Worker',
            },
        });

        if (checkResponse.ok) {
            // Repo exists, return its URL
            const existingRepo = await checkResponse.json() as { html_url: string };
            return {
                success: true,
                repoUrl: existingRepo.html_url,
            };
        }

        // Create new repository
        const response = await fetch(`${GITHUB_API}/orgs/local-brands/repos`, {
            method: 'POST',
            headers: {
                Authorization: `Bearer ${env.GITHUB_TOKEN}`,
                Accept: 'application/vnd.github.v3+json',
                'Content-Type': 'application/json',
                'User-Agent': 'LocalBrands-Worker',
            },
            body: JSON.stringify({
                name: repoName,
                description: 'Landing page generated by Local Brands',
                private: false,
                auto_init: true, // Initialize with README
                has_pages: true, // Enable GitHub Pages
            }),
        });

        if (!response.ok) {
            // If org doesn't exist, try creating under user account
            const userResponse = await fetch(`${GITHUB_API}/user/repos`, {
                method: 'POST',
                headers: {
                    Authorization: `Bearer ${env.GITHUB_TOKEN}`,
                    Accept: 'application/vnd.github.v3+json',
                    'Content-Type': 'application/json',
                    'User-Agent': 'LocalBrands-Worker',
                },
                body: JSON.stringify({
                    name: repoName,
                    description: 'Landing page generated by Local Brands',
                    private: false,
                    auto_init: true,
                }),
            });

            if (!userResponse.ok) {
                const errorData = await userResponse.text();
                console.error('GitHub create repo error:', errorData);
                return {
                    success: false,
                    error: `Failed to create repository: ${userResponse.status}`,
                };
            }

            const userRepoData = await userResponse.json() as { html_url: string };
            return {
                success: true,
                repoUrl: userRepoData.html_url,
            };
        }

        const repoData = await response.json() as { html_url: string };
        return {
            success: true,
            repoUrl: repoData.html_url,
        };

    } catch (error) {
        console.error('GitHub API error:', error);
        return {
            success: false,
            error: error instanceof Error ? error.message : 'Unknown error',
        };
    }
}

/**
 * Push landing page files to the GitHub repository
 */
export async function pushToGitHub(
    repoName: string,
    htmlContent: string,
    env: Env
): Promise<GitHubPushResult> {
    try {
        // Get the current user to determine the owner
        const userResponse = await fetch(`${GITHUB_API}/user`, {
            headers: {
                Authorization: `Bearer ${env.GITHUB_TOKEN}`,
                Accept: 'application/vnd.github.v3+json',
                'User-Agent': 'LocalBrands-Worker',
            },
        });

        if (!userResponse.ok) {
            return { success: false, error: 'Failed to get user info' };
        }

        const userData = await userResponse.json() as { login: string };
        const owner = userData.login;

        // Wait a moment for the repo to be fully initialized
        await new Promise(resolve => setTimeout(resolve, 2000));

        // Get the default branch's latest commit SHA
        const refResponse = await fetch(
            `${GITHUB_API}/repos/${owner}/${repoName}/git/refs/heads/main`,
            {
                headers: {
                    Authorization: `Bearer ${env.GITHUB_TOKEN}`,
                    Accept: 'application/vnd.github.v3+json',
                    'User-Agent': 'LocalBrands-Worker',
                },
            }
        );

        let baseSha: string;
        if (refResponse.ok) {
            const refData = await refResponse.json() as { object: { sha: string } };
            baseSha = refData.object.sha;
        } else {
            // Try master branch
            const masterResponse = await fetch(
                `${GITHUB_API}/repos/${owner}/${repoName}/git/refs/heads/master`,
                {
                    headers: {
                        Authorization: `Bearer ${env.GITHUB_TOKEN}`,
                        Accept: 'application/vnd.github.v3+json',
                        'User-Agent': 'LocalBrands-Worker',
                    },
                }
            );

            if (!masterResponse.ok) {
                return { success: false, error: 'Failed to get branch reference' };
            }

            const masterData = await masterResponse.json() as { object: { sha: string } };
            baseSha = masterData.object.sha;
        }

        // Create blob for index.html
        const blobResponse = await fetch(
            `${GITHUB_API}/repos/${owner}/${repoName}/git/blobs`,
            {
                method: 'POST',
                headers: {
                    Authorization: `Bearer ${env.GITHUB_TOKEN}`,
                    Accept: 'application/vnd.github.v3+json',
                    'Content-Type': 'application/json',
                    'User-Agent': 'LocalBrands-Worker',
                },
                body: JSON.stringify({
                    content: btoa(unescape(encodeURIComponent(htmlContent))),
                    encoding: 'base64',
                }),
            }
        );

        if (!blobResponse.ok) {
            return { success: false, error: 'Failed to create blob' };
        }

        const blobData = await blobResponse.json() as { sha: string };

        // Get the base tree
        const baseCommitResponse = await fetch(
            `${GITHUB_API}/repos/${owner}/${repoName}/git/commits/${baseSha}`,
            {
                headers: {
                    Authorization: `Bearer ${env.GITHUB_TOKEN}`,
                    Accept: 'application/vnd.github.v3+json',
                    'User-Agent': 'LocalBrands-Worker',
                },
            }
        );

        if (!baseCommitResponse.ok) {
            return { success: false, error: 'Failed to get base commit' };
        }

        const baseCommitData = await baseCommitResponse.json() as { tree: { sha: string } };

        // Create tree with index.html
        const treeResponse = await fetch(
            `${GITHUB_API}/repos/${owner}/${repoName}/git/trees`,
            {
                method: 'POST',
                headers: {
                    Authorization: `Bearer ${env.GITHUB_TOKEN}`,
                    Accept: 'application/vnd.github.v3+json',
                    'Content-Type': 'application/json',
                    'User-Agent': 'LocalBrands-Worker',
                },
                body: JSON.stringify({
                    base_tree: baseCommitData.tree.sha,
                    tree: [
                        {
                            path: 'index.html',
                            mode: '100644',
                            type: 'blob',
                            sha: blobData.sha,
                        },
                    ],
                }),
            }
        );

        if (!treeResponse.ok) {
            return { success: false, error: 'Failed to create tree' };
        }

        const treeData = await treeResponse.json() as { sha: string };

        // Create commit
        const commitResponse = await fetch(
            `${GITHUB_API}/repos/${owner}/${repoName}/git/commits`,
            {
                method: 'POST',
                headers: {
                    Authorization: `Bearer ${env.GITHUB_TOKEN}`,
                    Accept: 'application/vnd.github.v3+json',
                    'Content-Type': 'application/json',
                    'User-Agent': 'LocalBrands-Worker',
                },
                body: JSON.stringify({
                    message: '🚀 Deploy landing page via Local Brands',
                    tree: treeData.sha,
                    parents: [baseSha],
                }),
            }
        );

        if (!commitResponse.ok) {
            return { success: false, error: 'Failed to create commit' };
        }

        const commitData = await commitResponse.json() as { sha: string };

        // Update reference
        const updateRefResponse = await fetch(
            `${GITHUB_API}/repos/${owner}/${repoName}/git/refs/heads/main`,
            {
                method: 'PATCH',
                headers: {
                    Authorization: `Bearer ${env.GITHUB_TOKEN}`,
                    Accept: 'application/vnd.github.v3+json',
                    'Content-Type': 'application/json',
                    'User-Agent': 'LocalBrands-Worker',
                },
                body: JSON.stringify({
                    sha: commitData.sha,
                    force: true,
                }),
            }
        );

        if (!updateRefResponse.ok) {
            // Try master branch
            await fetch(
                `${GITHUB_API}/repos/${owner}/${repoName}/git/refs/heads/master`,
                {
                    method: 'PATCH',
                    headers: {
                        Authorization: `Bearer ${env.GITHUB_TOKEN}`,
                        Accept: 'application/vnd.github.v3+json',
                        'Content-Type': 'application/json',
                        'User-Agent': 'LocalBrands-Worker',
                    },
                    body: JSON.stringify({
                        sha: commitData.sha,
                        force: true,
                    }),
                }
            );
        }

        // Enable GitHub Pages
        await fetch(
            `${GITHUB_API}/repos/${owner}/${repoName}/pages`,
            {
                method: 'POST',
                headers: {
                    Authorization: `Bearer ${env.GITHUB_TOKEN}`,
                    Accept: 'application/vnd.github.v3+json',
                    'Content-Type': 'application/json',
                    'User-Agent': 'LocalBrands-Worker',
                },
                body: JSON.stringify({
                    source: {
                        branch: 'main',
                        path: '/',
                    },
                }),
            }
        );

        return {
            success: true,
            commitSha: commitData.sha,
        };

    } catch (error) {
        console.error('GitHub push error:', error);
        return {
            success: false,
            error: error instanceof Error ? error.message : 'Unknown error',
        };
    }
}
